# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: container remove --if-present
      run: docker stop portfolio && docker rm portfolio || true
    - name: Remove existing Docker image
      run: docker rmi ghelowee/portfolio:0 || true
    - name: Build Docker image
      run: docker build -t ghelowee/portfolio:0 .
    - name: Create Docker container
      run: docker create --name portfolio -p 5001:5001 --restart=always ghelowee/portfolio:0
    - name: Run Docker container
      run: docker start portfolio
